# Generated by Django 3.0.2 on 2020-01-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netblock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=15)),
                ('mask', models.IntegerField()),
                ('asn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asn.ASN')),
            ],
        ),
    ]
