# Generated by Django 3.2.12 on 2022-02-11 18:31

from django.db import migrations, models
import peermessage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeerMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('time', peermessage.models.ConvertingDateTimeField()),
                ('counter', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('neighbor_address_local', models.CharField(max_length=255)),
                ('neighbor_address_peer', models.CharField(max_length=255)),
                ('neighbor_asn_local', models.CharField(max_length=255)),
                ('neighbor_asn_peer', models.CharField(max_length=255)),
                ('neighbor_direction', models.CharField(max_length=255)),
                ('neighbor_state', models.CharField(max_length=255)),
                ('related_asn', models.CharField(max_length=255)),
                ('related_network', models.CharField(max_length=255)),
                ('raw', models.TextField()),
            ],
        ),
    ]
