# Generated by Django 3.2.12 on 2022-02-11 18:31

from django.db import migrations, models
import django.db.models.deletion
import flowSpec.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('announceBGP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowSpec',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('src_net', models.CharField(blank=True, max_length=18, null=True, validators=[flowSpec.models.FlowSpec.validate_srcnet])),
                ('dst_net', models.CharField(max_length=18, validators=[flowSpec.models.FlowSpec.validate_dstnet])),
                ('src_port', models.CharField(blank=True, max_length=255, null=True, validators=[flowSpec.models.FlowSpec.validate_port])),
                ('dst_port', models.CharField(blank=True, max_length=255, null=True, validators=[flowSpec.models.FlowSpec.validate_port])),
                ('t_proto', multiselectfield.db.fields.MultiSelectField(choices=[('UDP', 'UDP'), ('TCP', 'TCP'), ('ICMP', 'ICMP')], max_length=12)),
                ('policy', models.CharField(choices=[('accept', 'Accept'), ('discard', 'Discard'), ('rate-limit', 'Rate limit')], max_length=15)),
                ('rate_limit', models.IntegerField(blank=True, null=True, verbose_name='')),
                ('announce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announceBGP.announcebgp')),
            ],
        ),
    ]
