# Generated by Django 3.0.2 on 2022-02-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asn',
            name='gre_ip',
            field=models.CharField(max_length=15),
        ),
    ]
