# Generated by Django 3.2.12 on 2022-02-11 18:31

import announceBGP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netblock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceBGP',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('block', models.CharField(max_length=18, validators=[announceBGP.models.AnnounceBGP.validate_net])),
                ('netblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netblock.netblock')),
            ],
        ),
    ]
