# Generated by Django 3.0.2 on 2020-01-15 21:26

import announceBGP.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netblock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnounceBGP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=18, validators=[announceBGP.models.AnnounceBGP.validate_net])),
                ('netblock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netblock.Netblock')),
            ],
        ),
    ]
